logging.config: classpath:log4j2-stage.yml

#Actuator setup
management.endpoints.web.exposure.include: "*"
management.endpoints.jmx.exposure.exclude: "*"
management.endpoint.health.show-details: always

management.health.circuitbreakers.enabled: true
management.health.diskspace.enabled: false

server.port: 8080

scheduler.rest.core.pool.size: 2
scheduler.rest.max.pool.size: 5
scheduler.rest.keep.alive.time.secs: 120
scheduler.rest.queue.max.size: 50

scheduler.ext.core.pool.size: 2
scheduler.ext.max.pool.size: 5
scheduler.ext.keep.alive.time.secs: 120
scheduler.ext.queue.max.size: 500

spring:
  sql.init.platform: "postgres"
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/db"
    username: "user"
    password: "password"

security:
  jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub
    expiration-time-in-sec: 86400
  scrypt:
    cpu-cost: 16384
    memory-cost: 8

external-geoip-service:
  base-url: https://reallyfreegeoip.org
  socket-connection-timeout-millis: 6000
  read-timeout-millis: 2500
  write-timeout-millis: 2500

resilience4j.circuitbreaker:
  instances:
    external-geoip-service:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 30s
      failureRateThreshold: 2
      eventConsumerBufferSize: 10
  configs:
    default:
      registerHealthIndicator: true
