logging.config: classpath:log4j2-dev.yml

#Actuator setup
#Enabling only the info endpoint
management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true
management.endpoints.web.exposure.include: info
management.endpoints.jmx.exposure.exclude: "*"

server.port: 8080

scheduler.rest.core.pool.size: 2
scheduler.rest.max.pool.size: 5
scheduler.rest.keep.alive.time.secs: 120
scheduler.rest.queue.max.size: 50

scheduler.ext.core.pool.size: 2
scheduler.ext.max.pool.size: 5
scheduler.ext.keep.alive.time.secs: 120
scheduler.ext.queue.max.size: 500

spring:
  sql.init.platform: "postgres"
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/db"
    username: "user"
    password: "password"

external-geoip-service:
  base-url: https://reallyfreegeoip.org
  socket-connection-timeout-millis: 6000
  read-timeout-millis: 2500
  write-timeout-millis: 2500

logging.level.org.springframework.jdbc.core: TRACE